### PR TITLE
Fix double free bug

### LINKED ISSUE #60: SIGABRT after double free
I was fuzzying around and the program was able to generate a command to crash Yafc with SIGABRT signal. The shortest string in this case I found, is "; ;", without quotes. I'm on c119322. Here's the backtrace from gdb.

```
yafc> ; ;

xrealloc(0x663010, 0): Success
*** Error in `/home/jukka/src/myyafc/yafc': double free or corruption (fasttop): 0x0000000000663010 ***

Program received signal SIGABRT, Aborted.
0x00007ffff6fbe267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
55      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff6fbe267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007ffff6fbfeca in __GI_abort () at abort.c:89
#2  0x00007ffff7001c53 in __libc_message (do_abort=do_abort@entry=1, 
    fmt=fmt@entry=0x7ffff711a1a8 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff7009c69 in malloc_printerr (ptr=<optimized out>, 
    str=0x7ffff711a270 "double free or corruption (fasttop)", action=1) at malloc.c:4965
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3834
#5  0x00007ffff700d89c in __GI___libc_free (mem=<optimized out>) at malloc.c:2950
#6  0x000000000041c1b0 in xrealloc (ptr=0x663010, size=0) at src/libmhe/xmalloc.c:40
#7  0x000000000041b9b6 in split_args (str=str@entry=0x662f71 " ") at src/libmhe/args.c:140
#8  0x000000000041be31 in args_push_back (args=args@entry=0x662fb0, str=str@entry=0x662f71 " ")
    at src/libmhe/args.c:198
#9  0x0000000000406f4e in exe_cmdline (str=0x662f73 "", str@entry=0x662f70 "; ", 
    aliases_are_expanded=aliases_are_expanded@entry=false) at src/cmd.c:240
#10 0x000000000040746b in command_loop () at src/cmd.c:134
#11 0x0000000000405a95 in main (argc=<optimized out>, argv=<optimized out>, envp=<optimized out>) at src/main.c:458
```

xrealloc() is called with non-NULL ptr and size 0. realloc() is really just a call to free() then. ptr is used after free() in fprintf() and free()d again and the program crashes. In split_args(), str is " ", args->argc is 0, when xrealloc() is called.

I was able to come up with a some kind of a patch to fix this. I'm just a little hesitant to change code, because there are no tests. Have you thought about adding tests, btw?

### PR DESCRIPTION
**Pull request by fluks**
Fix parsing of a command string "; ;", which causes a double free.

Closes #60.

### CODE REVIEW

**Comment by fluks** [comment]
I guess that fprintf() is ok, asking a pointer's address isn't using that memory. I don't remember the standard.

File: src/libmhe/xmalloc.c [hunk 1]
```diff
@@ -33,8 +33,11 @@ void* xrealloc(void* ptr, size_t size)
...
   void* new_ptr = realloc(ptr, size);
   if (!new_ptr) {
-    fprintf(stderr, "\nxrealloc(%p, %zu): %s\n", ptr, size, strerror(errno));
-    free(ptr);
+    // If size is zero, free() was called, instead of realloc(). Don't use after free().
+    if (size != 0) {
+      fprintf(stderr, "\nxrealloc(%p, %zu): %s\n", ptr, size, strerror(errno));
+      free(ptr);
+    }
     exit(errno);
```
Comment (sebastinas) [inline src/libmhe/xmalloc.c]: I'd also move the `exit(errno)` to the new `if` block.

**Comment by fluks** [comment]
I added the condition to the upper if, like so.
https://gist.github.com/fluks/e94da1c29bb2315c62e1

Do you have a preference how I should update the PR? Just push another commit, can I --amend or something fancier?

**Comment by sebastinas** [comment]
I don't really have a preference. If you want to amend the previous commit, just go ahead.

**Comment by TheJosh** [comment]
+1 that looks better
